import { Category, Product, CartItem } from './types';

/**
 * Joe Tech product categories.
 *
 * `repairs` is a service category, it routes to the services page rather than
 * a product grid, because those are quoted jobs rather than stocked items.
 */
export const marketplaceCategories: Category[] = [
  {
    id: 'iphones-ipads',
    name: 'iPhones & iPads',
    shortName: 'iPhones',
    description:
      'Brand new and clean UK-used iPhones and iPads. Every unit is battery-tested, iCloud-clear and comes with a warranty.',
    icon: 'Smartphone',
    gradient: 'from-[#3626a7] to-[#281c7d]',
  },
  {
    id: 'android-phones',
    name: 'Android Phones',
    shortName: 'Android',
    description:
      'Samsung, Google Pixel, Tecno, Infinix and Xiaomi, from flagship power down to solid everyday budget phones.',
    icon: 'Smartphone',
    gradient: 'from-[#657ed4] to-[#3626a7]',
  },
  {
    id: 'laptops-tablets',
    name: 'Laptops & Tablets',
    shortName: 'Laptops',
    description:
      'MacBooks, business ultrabooks, gaming rigs and Android tablets. Configured, cleaned and ready to work.',
    icon: 'Laptop',
    gradient: 'from-[#657ed4] to-[#657ed4]',
  },
  {
    id: 'phone-accessories',
    name: 'Phone Accessories',
    shortName: 'Phone Gear',
    description:
      'Chargers, power banks, earbuds, cases and screen protection, all genuine parts, no counterfeits.',
    icon: 'Headphones',
    gradient: 'from-[#ff331f] to-[#cc2919]',
  },
  {
    id: 'laptop-accessories',
    name: 'Laptop Accessories',
    shortName: 'Laptop Gear',
    description:
      'Chargers, SSD and RAM upgrades, docking stations, keyboards, mice, cooling pads and bags.',
    icon: 'Keyboard',
    gradient: 'from-[#0d0106] to-[#3626a7]',
  },
  {
    id: 'gaming-setup',
    name: 'Gaming Monitors, Chairs & Table',
    shortName: 'Gaming',
    description:
      'High-refresh monitors, ergonomic gaming chairs, tables, mounts and the accessories that finish the setup.',
    icon: 'Gamepad2',
    gradient: 'from-[#cc2919] to-[#0d0106]',
  },
  {
    id: 'solar-power',
    name: 'Solar Machines & Devices',
    shortName: 'Solar',
    description:
      'Inverters, panels, lithium and tubular batteries, charge controllers and full solar kits, sized and installed for your load.',
    icon: 'Sun',
    gradient: 'from-[#657ed4] to-[#ff331f]',
  },
  {
    id: 'repairs',
    name: 'Repair & Maintenance Services',
    shortName: 'Repairs',
    description:
      'Screens, batteries, charging ports, water damage, laptop servicing and solar installation, diagnosed before you pay.',
    icon: 'Wrench',
    gradient: 'from-[#1a0f47] to-[#281c7d]',
    isService: true,
  },
];

/**
 * Starter catalog.
 *
 * These are realistic placeholders so the storefront reads as a real shop from
 * day one. Replace or edit them from the admin dashboard, anything added there
 * is stored in Supabase and takes precedence over this list.
 */
export const products: Product[] = [
  // ── iPhones & iPads ──────────────────────────────────────────────────────
  {
    id: 'jt-ip-01',
    name: 'iPhone 15 Pro Max 256GB',
    price: 1250000,
    category: 'iPhones & iPads',
    description:
      'Titanium build, A17 Pro chip and the 5x telephoto camera. Battery health 95%+, Face ID working, iCloud clear.',
    images: [],
    icon: 'Smartphone',
    condition: 'UK Used',
    specs: ['A17 Pro', '256GB', '48MP main camera', 'Battery 95%+'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-ip-02',
    name: 'iPhone 14 Pro 128GB',
    price: 850000,
    category: 'iPhones & iPads',
    description:
      'Dynamic Island, always-on ProMotion display and a superb triple camera. Clean unit, no face ID or screen issues.',
    images: [],
    icon: 'Smartphone',
    condition: 'UK Used',
    specs: ['A16 Bionic', '128GB', 'ProMotion 120Hz', 'Battery 90%+'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-ip-03',
    name: 'iPhone 13 128GB',
    price: 560000,
    category: 'iPhones & iPads',
    description:
      'Still one of the best value iPhones, with excellent battery life, great cameras and years of iOS updates ahead.',
    images: [],
    icon: 'Smartphone',
    condition: 'UK Used',
    specs: ['A15 Bionic', '128GB', 'Dual 12MP', 'Battery 88%+'],
    inStock: true,
  },
  {
    id: 'jt-ip-04',
    name: 'iPhone 12 64GB',
    price: 380000,
    category: 'iPhones & iPads',
    description: 'Clean, dependable iPhone with 5G, OLED display and MagSafe charging support.',
    images: [],
    icon: 'Smartphone',
    condition: 'UK Used',
    specs: ['A14 Bionic', '64GB', 'Super Retina XDR', '5G'],
    inStock: true,
  },
  {
    id: 'jt-ip-05',
    name: 'iPad Air (5th Gen) 64GB',
    price: 620000,
    category: 'iPhones & iPads',
    description:
      'M1 chip in a tablet that handles design work, editing and split-screen multitasking without breaking a sweat.',
    images: [],
    icon: 'Tablet',
    condition: 'Brand New',
    specs: ['Apple M1', '64GB', '10.9" Liquid Retina', 'Wi-Fi'],
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-ip-06',
    name: 'iPad 10th Gen 64GB',
    price: 450000,
    category: 'iPhones & iPads',
    description: 'The everyday iPad, for school, streaming, browsing and notes, with all-day battery.',
    images: [],
    icon: 'Tablet',
    condition: 'Brand New',
    specs: ['A14 Bionic', '64GB', '10.9" Liquid Retina', 'USB-C'],
    isNew: true,
    inStock: true,
  },

  // ── Android Phones ───────────────────────────────────────────────────────
  {
    id: 'jt-an-01',
    name: 'Samsung Galaxy S24 Ultra 256GB',
    price: 1150000,
    category: 'Android Phones',
    description:
      'Titanium frame, built-in S Pen, 200MP camera and the brightest display Samsung has shipped.',
    images: [],
    icon: 'Smartphone',
    condition: 'Brand New',
    specs: ['Snapdragon 8 Gen 3', '256GB', '200MP camera', 'S Pen included'],
    isTrending: true,
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-an-02',
    name: 'Google Pixel 8 Pro 128GB',
    price: 780000,
    category: 'Android Phones',
    description:
      'The best point-and-shoot camera on Android, with seven years of guaranteed Google updates.',
    images: [],
    icon: 'Smartphone',
    condition: 'UK Used',
    specs: ['Google Tensor G3', '128GB', '50MP triple camera', '7 yrs updates'],
    inStock: true,
  },
  {
    id: 'jt-an-03',
    name: 'Samsung Galaxy S23 256GB',
    price: 720000,
    category: 'Android Phones',
    description: 'Compact flagship with superb battery efficiency and a bright 120Hz AMOLED screen.',
    images: [],
    icon: 'Smartphone',
    condition: 'UK Used',
    specs: ['Snapdragon 8 Gen 2', '256GB', '120Hz AMOLED', 'Wireless charging'],
    inStock: true,
  },
  {
    id: 'jt-an-04',
    name: 'Samsung Galaxy A55 128GB',
    price: 420000,
    category: 'Android Phones',
    description:
      'The sweet spot in Samsung mid-range, with premium feel, clean software and a genuinely good camera.',
    images: [],
    icon: 'Smartphone',
    condition: 'Brand New',
    specs: ['Exynos 1480', '128GB', '120Hz Super AMOLED', '5000mAh'],
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-an-05',
    name: 'Infinix Note 40 Pro 256GB',
    price: 310000,
    category: 'Android Phones',
    description: 'Huge battery, 45W fast charge and a big AMOLED screen at a very fair price.',
    images: [],
    icon: 'Smartphone',
    condition: 'Brand New',
    specs: ['Helio G99', '256GB', '5000mAh', '45W fast charge'],
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-an-06',
    name: 'Xiaomi Redmi Note 13 Pro 256GB',
    price: 295000,
    category: 'Android Phones',
    description: 'A 200MP camera and 120Hz AMOLED display for well under three hundred thousand.',
    images: [],
    icon: 'Smartphone',
    condition: 'Brand New',
    specs: ['Snapdragon 7s Gen 2', '256GB', '200MP camera', '67W charge'],
    inStock: true,
  },
  {
    id: 'jt-an-07',
    name: 'Tecno Camon 30 256GB',
    price: 285000,
    category: 'Android Phones',
    description: 'Strong everyday performer with a bright display and dependable all-day battery.',
    images: [],
    icon: 'Smartphone',
    condition: 'Brand New',
    specs: ['Helio G99', '256GB', '120Hz AMOLED', '70W charge'],
    inStock: true,
  },

  // ── Laptops & Tablets ────────────────────────────────────────────────────
  {
    id: 'jt-lt-01',
    name: 'MacBook Pro 14" M3 512GB',
    price: 2450000,
    category: 'Laptops & Tablets',
    description:
      'Liquid Retina XDR display and all-day battery. Built for video editing, development and design work.',
    images: [],
    icon: 'Laptop',
    condition: 'Brand New',
    specs: ['Apple M3', '16GB RAM', '512GB SSD', '14" Liquid Retina XDR'],
    isTrending: true,
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-lt-02',
    name: 'ASUS ROG Strix G16 RTX 4060',
    price: 1850000,
    category: 'Laptops & Tablets',
    description:
      'Serious gaming laptop with a 165Hz panel, RTX 4060 graphics and a cooling system that holds up under load.',
    images: [],
    icon: 'Laptop',
    condition: 'Brand New',
    specs: ['Core i7-13650HX', '16GB RAM', 'RTX 4060 8GB', '165Hz display'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-lt-03',
    name: 'MacBook Air M2 256GB',
    price: 1350000,
    category: 'Laptops & Tablets',
    description: 'Thin, silent and fanless with genuinely all-day battery. The best everyday laptop.',
    images: [],
    icon: 'Laptop',
    condition: 'UK Used',
    specs: ['Apple M2', '8GB RAM', '256GB SSD', '13.6" Liquid Retina'],
    inStock: true,
  },
  {
    id: 'jt-lt-04',
    name: 'Dell XPS 15, Core i7, 16GB',
    price: 1180000,
    category: 'Laptops & Tablets',
    description: 'Premium Windows ultrabook with a stunning near-borderless 15" display.',
    images: [],
    icon: 'Laptop',
    condition: 'UK Used',
    specs: ['Core i7-12700H', '16GB RAM', '512GB SSD', '15.6" FHD+'],
    inStock: true,
  },
  {
    id: 'jt-lt-05',
    name: 'Samsung Galaxy Tab S9 128GB',
    price: 780000,
    category: 'Laptops & Tablets',
    description: 'Flagship Android tablet with an included S Pen and a gorgeous AMOLED display.',
    images: [],
    icon: 'Tablet',
    condition: 'Brand New',
    specs: ['Snapdragon 8 Gen 2', '128GB', '11" AMOLED', 'S Pen included'],
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-lt-06',
    name: 'HP EliteBook 840 G8, Core i7',
    price: 680000,
    category: 'Laptops & Tablets',
    description:
      'Business-grade build with a great keyboard. Our most reliable pick for office and school work.',
    images: [],
    icon: 'Laptop',
    condition: 'UK Used',
    specs: ['Core i7-1165G7', '16GB RAM', '512GB SSD', '14" FHD'],
    inStock: true,
  },
  {
    id: 'jt-lt-07',
    name: 'Lenovo ThinkPad T14, Core i5',
    price: 520000,
    category: 'Laptops & Tablets',
    description: 'Legendary ThinkPad keyboard and durability. Excellent value workhorse.',
    images: [],
    icon: 'Laptop',
    condition: 'UK Used',
    specs: ['Core i5-1135G7', '16GB RAM', '256GB SSD', '14" FHD'],
    inStock: true,
  },

  // ── Phone Accessories ────────────────────────────────────────────────────
  {
    id: 'jt-pa-01',
    name: 'AirPods Pro (2nd Generation)',
    price: 185000,
    category: 'Phone Accessories',
    description:
      'Active noise cancellation, adaptive transparency and USB-C charging. Sealed, with warranty.',
    images: [],
    icon: 'Headphones',
    condition: 'Brand New',
    specs: ['Active noise cancellation', 'USB-C case', 'Up to 6h playback'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-pa-02',
    name: 'Anker PowerCore 20,000mAh Power Bank',
    price: 38000,
    category: 'Phone Accessories',
    description: 'Charges a phone four to five times over. 20W USB-C Power Delivery in and out.',
    images: [],
    icon: 'BatteryCharging',
    condition: 'Brand New',
    specs: ['20,000mAh', '20W USB-C PD', 'Charges 4-5 times'],
    inStock: true,
  },
  {
    id: 'jt-pa-03',
    name: 'Baseus 65W GaN Fast Charger',
    price: 32000,
    category: 'Phone Accessories',
    description: 'One compact brick that fast-charges a phone, tablet and laptop. Three ports.',
    images: [],
    icon: 'Zap',
    condition: 'Brand New',
    specs: ['65W total', '2x USB-C + 1x USB-A', 'GaN technology'],
    inStock: true,
  },
  {
    id: 'jt-pa-04',
    name: 'Oraimo FreePods 4 Wireless Earbuds',
    price: 28000,
    category: 'Phone Accessories',
    description: 'Excellent value earbuds with noise cancellation and a long-lasting charging case.',
    images: [],
    icon: 'Headphones',
    condition: 'Brand New',
    specs: ['ENC noise cancellation', 'Up to 30h with case', 'Bluetooth 5.3'],
    inStock: true,
  },
  {
    id: 'jt-pa-05',
    name: 'MagSafe Wireless Charging Stand',
    price: 26000,
    category: 'Phone Accessories',
    description: 'Snaps on magnetically and charges at 15W while holding the phone at a viewing angle.',
    images: [],
    icon: 'Zap',
    condition: 'Brand New',
    specs: ['15W magnetic', 'Adjustable angle', 'iPhone 12 and newer'],
    inStock: true,
  },
  {
    id: 'jt-pa-06',
    name: 'Apple 20W USB-C Power Adapter',
    price: 18500,
    category: 'Phone Accessories',
    description: 'The genuine article, fast, safe charging that will not cook your battery.',
    images: [],
    icon: 'Zap',
    condition: 'Brand New',
    specs: ['20W USB-C', 'Genuine Apple', 'Fast charge iPhone 8+'],
    inStock: true,
  },
  {
    id: 'jt-pa-07',
    name: 'Braided USB-C to Lightning Cable (2m)',
    price: 6500,
    category: 'Phone Accessories',
    description: 'Nylon-braided and MFi-certified, survives daily use far longer than the stock cable.',
    images: [],
    icon: 'Cable',
    condition: 'Brand New',
    specs: ['2 metres', 'MFi certified', 'Nylon braided'],
    inStock: true,
  },
  {
    id: 'jt-pa-08',
    name: 'Tempered Glass Screen Protector',
    price: 4500,
    category: 'Phone Accessories',
    description: '9H tempered glass, fitted free in-store when you buy it with us.',
    images: [],
    icon: 'ShieldCheck',
    condition: 'Brand New',
    specs: ['9H hardness', 'Oleophobic coating', 'Free fitting in-store'],
    inStock: true,
  },

  // ── Laptop Accessories ───────────────────────────────────────────────────
  {
    id: 'jt-la-01',
    name: 'Samsung 1TB NVMe SSD',
    price: 145000,
    category: 'Laptop Accessories',
    description:
      'The single best upgrade for an ageing laptop. We clone your existing drive free of charge.',
    images: [],
    icon: 'HardDrive',
    condition: 'Brand New',
    specs: ['1TB capacity', 'NVMe PCIe', 'Up to 3,500MB/s', 'Free cloning'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-la-02',
    name: 'USB-C Docking Station (11-in-1)',
    price: 85000,
    category: 'Laptop Accessories',
    description:
      'Turns one USB-C port into dual monitors, ethernet, SD card reader and four USB ports.',
    images: [],
    icon: 'Usb',
    condition: 'Brand New',
    specs: ['Dual 4K HDMI', 'Gigabit ethernet', '100W passthrough', 'SD/microSD'],
    inStock: true,
  },
  {
    id: 'jt-la-03',
    name: 'Logitech MX Master 3S',
    price: 68000,
    category: 'Laptop Accessories',
    description: 'The mouse most developers and designers settle on. Silent clicks, superb scroll wheel.',
    images: [],
    icon: 'Mouse',
    condition: 'Brand New',
    specs: ['8K DPI', 'Quiet clicks', 'Multi-device', 'USB-C rechargeable'],
    inStock: true,
  },
  {
    id: 'jt-la-04',
    name: 'Mechanical Keyboard (TKL, Hot-swap)',
    price: 55000,
    category: 'Laptop Accessories',
    description: 'Tenkeyless mechanical board with hot-swappable switches and RGB backlighting.',
    images: [],
    icon: 'Keyboard',
    condition: 'Brand New',
    specs: ['Tenkeyless', 'Hot-swappable', 'RGB backlit', 'USB-C detachable'],
    inStock: true,
  },
  {
    id: 'jt-la-05',
    name: '16GB DDR4 Laptop RAM (3200MHz)',
    price: 48000,
    category: 'Laptop Accessories',
    description: 'Doubles most laptops to 32GB. Free installation and compatibility check in-store.',
    images: [],
    icon: 'MemoryStick',
    condition: 'Brand New',
    specs: ['16GB SODIMM', 'DDR4 3200MHz', 'Free installation'],
    inStock: true,
  },
  {
    id: 'jt-la-06',
    name: 'Anti-theft Laptop Backpack',
    price: 32000,
    category: 'Laptop Accessories',
    description: 'Padded 15.6" compartment, hidden zips, water-resistant shell and a USB pass-through.',
    images: [],
    icon: 'Backpack',
    condition: 'Brand New',
    specs: ['Fits 15.6"', 'Water resistant', 'Hidden zips', 'USB pass-through'],
    inStock: true,
  },
  {
    id: 'jt-la-07',
    name: 'RGB Laptop Cooling Pad (6 Fans)',
    price: 24000,
    category: 'Laptop Accessories',
    description: 'Keeps gaming laptops from throttling during long sessions. Adjustable height.',
    images: [],
    icon: 'Fan',
    condition: 'Brand New',
    specs: ['6 fans', 'Adjustable height', 'RGB lighting', 'Fits up to 17"'],
    inStock: true,
  },
  {
    id: 'jt-la-08',
    name: 'Universal 90W Laptop Charger',
    price: 22000,
    category: 'Laptop Accessories',
    description: 'Ships with eight tips covering HP, Dell, Lenovo, Asus and Acer. Surge protected.',
    images: [],
    icon: 'Plug',
    condition: 'Brand New',
    specs: ['90W output', '8 interchangeable tips', 'Surge protected'],
    inStock: true,
  },

  // ── Gaming ───────────────────────────────────────────────────────────────
  {
    id: 'jt-gm-01',
    name: '27" QHD 165Hz Gaming Monitor',
    price: 385000,
    category: 'Gaming Monitors, Chairs & Table',
    description:
      '1440p at 165Hz with 1ms response and FreeSync. The sweet spot for competitive gaming.',
    images: [],
    icon: 'Monitor',
    condition: 'Brand New',
    specs: ['27" QHD 2560x1440', '165Hz', '1ms response', 'FreeSync Premium'],
    isTrending: true,
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-gm-02',
    name: '24" FHD 144Hz Gaming Monitor',
    price: 245000,
    category: 'Gaming Monitors, Chairs & Table',
    description: 'The value pick for a high refresh rate without the flagship price.',
    images: [],
    icon: 'Monitor',
    condition: 'Brand New',
    specs: ['24" FHD 1920x1080', '144Hz', '1ms response', 'HDMI + DisplayPort'],
    inStock: true,
  },
  {
    id: 'jt-gm-03',
    name: 'Ergonomic Gaming Chair with RGB',
    price: 210000,
    category: 'Gaming Monitors, Chairs & Table',
    description:
      'Lumbar and neck support, 4D armrests and a 155° recline. Built for long sessions, not showroom photos.',
    images: [],
    icon: 'Armchair',
    condition: 'Brand New',
    specs: ['155° recline', '4D armrests', 'Lumbar support', 'RGB base'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-gm-04',
    name: 'Gaming Desk with RGB Surface (140cm)',
    price: 175000,
    category: 'Gaming Monitors, Chairs & Table',
    description: 'Carbon-fibre texture top, cable management, headphone hook and cup holder.',
    images: [],
    icon: 'Table',
    condition: 'Brand New',
    specs: ['140cm wide', 'RGB edge lighting', 'Cable management', 'Steel frame'],
    inStock: true,
  },
  {
    id: 'jt-gm-05',
    name: 'Xbox Wireless Controller',
    price: 72000,
    category: 'Gaming Monitors, Chairs & Table',
    description: 'Works with Xbox, PC and mobile. Textured grips and a hybrid D-pad.',
    images: [],
    icon: 'Gamepad2',
    condition: 'Brand New',
    specs: ['Bluetooth + USB-C', 'Xbox / PC / mobile', 'Textured grips'],
    inStock: true,
  },
  {
    id: 'jt-gm-06',
    name: 'Dual Monitor Arm Mount',
    price: 65000,
    category: 'Gaming Monitors, Chairs & Table',
    description: 'Gas-spring arms that free up the whole desk surface. Fits 17"–32" screens.',
    images: [],
    icon: 'Monitor',
    condition: 'Brand New',
    specs: ['Fits 17"-32"', 'Gas spring', 'VESA 75/100', 'Clamp + grommet'],
    inStock: true,
  },
  {
    id: 'jt-gm-07',
    name: '7.1 Surround Gaming Headset',
    price: 58000,
    category: 'Gaming Monitors, Chairs & Table',
    description: 'Virtual surround positioning, noise-cancelling boom mic and memory-foam earcups.',
    images: [],
    icon: 'Headphones',
    condition: 'Brand New',
    specs: ['7.1 virtual surround', 'Detachable mic', 'Memory foam', 'USB + 3.5mm'],
    inStock: true,
  },
  {
    id: 'jt-gm-08',
    name: 'XXL RGB Mouse Pad (90x40cm)',
    price: 15000,
    category: 'Gaming Monitors, Chairs & Table',
    description: 'Covers keyboard and mouse, stitched edges, 14 lighting modes.',
    images: [],
    icon: 'Square',
    condition: 'Brand New',
    specs: ['90x40cm', '14 RGB modes', 'Stitched edges', 'Non-slip base'],
    inStock: true,
  },

  // ── Solar ────────────────────────────────────────────────────────────────
  {
    id: 'jt-sp-01',
    name: 'Complete 3KVA Solar Kit (Installed)',
    price: 1450000,
    category: 'Solar Machines & Devices',
    description:
      'Everything you need: 3KVA inverter, four 300W panels, 200Ah lithium battery, controller, cabling and full installation.',
    images: [],
    icon: 'Sun',
    condition: 'Brand New',
    specs: ['3KVA inverter', '4x 300W panels', '200Ah lithium', 'Installation included'],
    isTrending: true,
    isNew: true,
    inStock: true,
  },
  {
    id: 'jt-sp-02',
    name: '5KVA Hybrid Solar Inverter',
    price: 780000,
    category: 'Solar Machines & Devices',
    description:
      'Pure sine wave hybrid inverter with a built-in MPPT controller. Runs a full household load.',
    images: [],
    icon: 'Zap',
    condition: 'Brand New',
    specs: ['5KVA / 48V', 'Pure sine wave', 'Built-in MPPT', 'Wi-Fi monitoring'],
    isTrending: true,
    inStock: true,
  },
  {
    id: 'jt-sp-03',
    name: '200Ah LiFePO4 Lithium Battery',
    price: 680000,
    category: 'Solar Machines & Devices',
    description:
      'Six thousand cycles and a ten-year design life, replaces four tubular batteries and outlasts them many times over.',
    images: [],
    icon: 'BatteryCharging',
    condition: 'Brand New',
    specs: ['200Ah / 51.2V', '6000+ cycles', 'Built-in BMS', '10-year design life'],
    inStock: true,
  },
  {
    id: 'jt-sp-04',
    name: '3.5KVA Solar Inverter',
    price: 520000,
    category: 'Solar Machines & Devices',
    description: 'Sized for a flat or small home, fans, lights, TV, fridge and laptops.',
    images: [],
    icon: 'Zap',
    condition: 'Brand New',
    specs: ['3.5KVA / 24V', 'Pure sine wave', 'MPPT controller', 'LCD display'],
    inStock: true,
  },
  {
    id: 'jt-sp-05',
    name: '220Ah Tubular Battery',
    price: 285000,
    category: 'Solar Machines & Devices',
    description: 'Deep-cycle tubular battery, the dependable, budget-friendly storage option.',
    images: [],
    icon: 'BatteryCharging',
    condition: 'Brand New',
    specs: ['220Ah / 12V', 'Deep cycle', 'Low maintenance', '18-month warranty'],
    inStock: true,
  },
  {
    id: 'jt-sp-06',
    name: '300W Monocrystalline Solar Panel',
    price: 125000,
    category: 'Solar Machines & Devices',
    description: 'High-efficiency mono panel with an anodised aluminium frame built for harsh sun.',
    images: [],
    icon: 'Sun',
    condition: 'Brand New',
    specs: ['300W output', 'Monocrystalline', '25-year output warranty', 'IP67 junction box'],
    inStock: true,
  },
  {
    id: 'jt-sp-07',
    name: '60A MPPT Charge Controller',
    price: 95000,
    category: 'Solar Machines & Devices',
    description: 'Extracts up to 30% more from your panels than an equivalent PWM controller.',
    images: [],
    icon: 'Gauge',
    condition: 'Brand New',
    specs: ['60A MPPT', '12/24/48V auto', 'LCD display', 'Up to 30% more yield'],
    inStock: true,
  },
  {
    id: 'jt-sp-08',
    name: 'Solar Rechargeable Standing Fan',
    price: 45000,
    category: 'Solar Machines & Devices',
    description: 'Runs off its own panel or mains. Includes an LED light and phone charging port.',
    images: [],
    icon: 'Fan',
    condition: 'Brand New',
    specs: ['16" blade', 'Solar + AC charging', 'LED light', 'USB charge out'],
    inStock: true,
  },
];

/**
 * Repair and maintenance services. Priced "from", the final quote depends on
 * the diagnosis, which is always free.
 */
export const repairServices = [
  {
    id: 'svc-01',
    name: 'iPhone Screen Replacement',
    fromPrice: 30000,
    icon: 'Smartphone',
    turnaround: '1–3 hours',
    description: 'Original-quality OLED and LCD panels fitted, with True Tone preserved where possible.',
  },
  {
    id: 'svc-02',
    name: 'Android Screen Replacement',
    fromPrice: 15000,
    icon: 'Smartphone',
    turnaround: '1–3 hours',
    description: 'Samsung, Tecno, Infinix, Xiaomi and Pixel screens replaced with tested panels.',
  },
  {
    id: 'svc-03',
    name: 'Laptop Battery Replacement',
    fromPrice: 16500,
    icon: 'BatteryCharging',
    turnaround: 'Under 1 hour',
    description: 'Genuine-capacity laptop batteries fitted. Old cell disposed of safely.',
  },
  {
    id: 'svc-04',
    name: 'Laptop Screen Replacement',
    fromPrice: 18000,
    icon: 'Laptop',
    turnaround: '1–2 days',
    description: 'Cracked, flickering or dead laptop displays replaced, matched to your exact model.',
  },
  {
    id: 'svc-05',
    name: 'Charging Port Repair',
    fromPrice: 15000,
    icon: 'Plug',
    turnaround: '1–3 hours',
    description: 'Loose or dead charging ports rebuilt at board level rather than bodged.',
  },
  {
    id: 'svc-06',
    name: 'Water Damage Recovery',
    fromPrice: 30000,
    icon: 'Droplets',
    turnaround: '1–3 days',
    description: 'Full ultrasonic board clean and component-level repair. Bring it in as soon as you can.',
  },
  {
    id: 'svc-07',
    name: 'OS Install & Data Recovery',
    fromPrice: 5000,
    icon: 'HardDrive',
    turnaround: 'Same day',
    description: 'Windows or macOS reinstall, virus removal, and recovery of files from failing drives.',
  },
  {
    id: 'svc-08',
    name: 'Solar & Inverter Installation',
    fromPrice: 40000,
    // Shown next to the price itself, not just buried in the description,
    // so it is clear before a customer even reads further that this covers
    // labour only, not the panels/inverter/battery being installed.
    priceNote: 'for workmanship',
    icon: 'Sun',
    turnaround: '1–2 days',
    description: 'Load assessment, mounting, wiring and commissioning by our engineers. Workmanship only, parts and materials are quoted separately.',
  },
] as const;

/** Formatted Naira amount (symbol + number). */
export const formatPrice = (price: number) =>
  `₦${price.toLocaleString('en-NG', { maximumFractionDigits: 0 })}`;

export const getCategoryById = (id: string) => marketplaceCategories.find((c) => c.id === id);

/** True once a product has at least one priced variant (e.g. storage size). */
export const hasVariants = (product: Product) => !!product.variants && product.variants.length > 0;

/**
 * The price to show for a product before any variant is picked: the
 * cheapest variant's price when it has variants, otherwise the flat price.
 * Everywhere a product is listed (cards, admin tables, the AI chat's
 * inventory list) shows this "from" price rather than the flat one, so it
 * never lies by quoting the base price of a product that actually starts
 * cheaper (or, if the admin left the base price stale, more expensive).
 */
export const getDisplayPrice = (product: Product): number =>
  hasVariants(product) ? Math.min(...product.variants!.map((v) => v.price)) : product.price;

/** The highest variant price, for a "from X to Y" range in the AI chat's inventory list. */
export const getMaxVariantPrice = (product: Product): number =>
  hasVariants(product) ? Math.max(...product.variants!.map((v) => v.price)) : product.price;

/** A cart line's real price is its chosen variant's, falling back to the
 *  product's flat price for items with no variants. Every cart/checkout
 *  total must read the price through this, never `item.product.price`
 *  directly, or a variant pick silently gets ignored in the math. */
export const getCartItemPrice = (item: CartItem): number =>
  item.selectedVariant?.price ?? item.product.price;

export const getCartItemOriginalPrice = (item: CartItem): number | undefined =>
  item.selectedVariant ? item.selectedVariant.originalPrice : item.product.originalPrice;
